client/src/components/Header.jsx
client/src/components/Hero.jsx

- Done #19 
https://github.com/adarsh-singh01/PrithWe/assets/142779809/6e467755-f16e-4ac5-8ab4-131dcb29f631

Fix navbar sticky

---

Learn.md

Modified the Learn.md and incorporated changes in .env as in the readme file
Thanks

Modified the Learn.md 

---

client/src/App.jsx
client/src/components/BusinessForm.jsx
client/src/components/Header.jsx
client/src/components/HouseholdForm.jsx
client/src/components/LoginForm.jsx
client/src/components/RegisterForm.jsx
client/src/pages/Login.jsx

Fixes: #7 
Description: 
1. Login and logout was forcibly reloading the website which results in bad experince to the user. I have implemented the same it will just redirect to the desired routes for both login and logout function without reloading which increases the User Experience.
2. I have improved the toastify notification as the ToastContainer and the respective css is written in all the required components. My approach to place it in the parent container i.e (App.jsx) such that no need of writing the toast container to all the components for rendering unneccesarily.

Fixed the force reload issue and improved the toastify notification

---

client/src/components/BusinessForm.jsx
client/src/components/HouseholdForm.jsx
package-lock.json
package.json

Fixes: #8 
Added error message and input sanitization. Will only allow to enter the valid input
https://github.com/adarsh-singh01/PrithWe/assets/133234867/e67fea67-152b-4afd-9210-8413d6533104

[Fixes]: Invalid Input Sanitization #8

---

client/package-lock.json
client/package.json
client/src/components/Header.jsx
client/src/components/LoginForm.jsx
client/src/components/RegisterForm.jsx

This pull request introduces the react-icons library to the project and integrates the eye icon for toggling password visibility in both the login and sign-up forms.
- Added the react-icons library to the project dependencies.
- Imported the eye icon from react-icons to be used in the password input fields.
- Implemented functionality to toggle the visibility of the password in the login form.
- Implemented functionality to toggle the visibility of the password in the sign-up form.
- This change enhances the user experience by allowing users to easily see and verify their password entries.
- No breaking changes introduced.

Toggle password

---

client/src/App.jsx
client/src/components/LoginForm.jsx
client/src/components/RegisterForm.jsx
client/src/pages/VerifyEmail.jsx
package-lock.json
package.json
server/Authentication.js
server/SendOTP.js
server/dbCommands.sql

User Verification added using otp. Solved Issue No. #35 Under GSSOC'24. Please check this and merge to main branch
https://github.com/adarsh-singh01/PrithWe/assets/108013711/155c312f-a55f-4db9-9cb1-5701e372ae3d

User Verification added

---

client/src/App.jsx
client/src/components/LoginForm.jsx
client/src/pages/ResetPassword.jsx
client/src/pages/VerifyEmail.jsx
package-lock.json
server/Authentication.js
server/SendOTP.js
server/db.js

Added Reset Password Feature where User can Reset his/her password forgot by any chance.

Added Forgot Password Feature

---

client/src/App.jsx
client/src/Scrollbar.css

Scrollbar with same theme added to enhance the UI.
Fixes #44

Added Custom Scrollbar

---

client/src/components/Header.jsx

add click handler function on menu when user click on any menu its automatically close 
https://github.com/adarsh-singh01/PrithWe/assets/140513098/3f7dda99-2489-432a-ae73-cfe6b8001d0f
closes #31

Handle menu toggle collapse menu when user click on it

---

client/src/App.css

**Description:**
This PR fixes the padding of the entire website,which was causing problems in the overall look of the website.
**Issue Mentioned:**
- Fixes #72
**Changes Made:**
- Removed padding from the `#root` id in `App.css` .
**ScreenShots:**
**Additional Context:**
N/A

[Bug]: Incorrect padding of the website

---

client/src/App.css

The issue of Scrollbar appearing at the bottom after hovering on the main scrollbar has been fixed.
Fixes #80

Fixed Scrollbar issue

---

server/EmailTemplate/emailTemplate.html
server/SendOTP.js

Solves #77 .
@adarsh-singh01 Please review.The way i have written is because redering on the email has some limitations of css.
This is what it looks finally.
https://github.com/adarsh-singh01/PrithWe/assets/105922142/81a8cc20-0d8d-43e1-a6dc-45eb8b74d749

"AddedProfessinalEmailSender"

---

client/src/App.jsx
client/src/Layout.jsx
client/src/components/UserDetailsSection.jsx
client/src/components/UserList.jsx
client/src/pages/UserDetails.jsx
package-lock.json
package.json
server/adminData.js
server/businessData.js

Solved Issue No. #69  under GSSOC'24. In admin Section admin can see User Details on clicking on the specific User.

Added User Details in admin Section

---

client/src/App.css
client/src/components/Accordian/Accordian.jsx
client/src/pages/Home.jsx

We have set the accordian in our home page
https://github.com/adarsh-singh01/PrithWe/assets/109230049/d892a435-ec17-45dd-8bbd-1f8e15bd5156

accordian set

---

client/src/components/BusinessForm.jsx
client/src/components/HouseholdForm.jsx
client/src/components/HouseholdResult.jsx
package-lock.json
package.json
server/businessData.js
server/dbCommands.sql
server/householdData.js

Solved Issue No. #94
For Business Account
For Household Account

Added AI integration for recommendation

---

client/src/pages/ResetPassword.jsx
client/src/pages/VerifyEmail.jsx
package-lock.json
package.json

With this update the following changes have been implemented
1. Unreadable texts changed to readable
2. Resolved Dark mode bugs
3. Updated theme of VerifyEmail & ResetPassword pages for consistency with website.
4. Minor Tweaks such as Focus ring changed to green to match overall theme of the website
5. Resolves #89 
**Previous UI:-** 
**Previous Focus ring -** 
**Previous Reset Password page**
.
.
.
**Updated UI:-** 
**Updated Focus ring color changed to green to match the website's overall theme -** 
**Updated Reset Password Page**

Resolves Bug No.#89 & Major UI Changes on VerifyEmail & ResetPassword Pages

---

client/package-lock.json
client/package.json
client/src/App.css
client/src/components/Header.jsx

After opening dialog box by click on hamburger that icon should be close icon #76

After opening dialog box by click on hamburger that icon should be close icon #76

---

client/src/components/UserDetailsSection.jsx

Fix in UI of User Details (Admin Panel)

---

client/src/components/Footer2.jsx
client/src/components/Visitor.jsx

issue #130 solved
https://github.com/adarsh-singh01/PrithWe/assets/125277258/97024d03-2aec-459b-9548-55a70f6af520

feat: visitor count added in the web page

---

client/package.json
client/src/components/Accordian/Accordian.jsx
client/src/components/BelowHero.jsx
client/src/components/Header.jsx
client/src/components/Hero.jsx
client/src/components/InfoCard.jsx

issue #108 solved
https://github.com/adarsh-singh01/PrithWe/assets/125277258/ce4c8e89-8df0-4caa-806a-91e6ef9a0873

Feat: Home page animation added

---

README.md

Added OAuth guide 
